- src/pages/Search.tsx
- Create 'Add an agent' card
- Create 'Add an agent' button in card
> Create 'Add an agent' card

- src/components/SearchBar.tsx
- src/pages/Search.tsx
- src/stories/SearchBar.stories.tsx
Simple component to codify consistent styles for search inputs.
> [PRO-121] Add SearchBar component

- src/router.tsx
Easier to read and reason about, less lines of code.
> [PRO-143] Refactor router to use JSX elements

- src/api/agents.ts
- src/components/SelectOfficeModal.tsx
- src/pages/AgentNew.tsx
- Add `create` function to `ApiAgent`
- Add handler to office onClick
- Add form state and functionality
- Add form submission to API with basic error handling on `AgentNew` component
~**WIP**~ 
~- Add autofocusing to name fields (do we have any best practices for this?)~
~- Format inputs to `firstName` and `lastName` fields (capitalize, etc., Any best practices for this given the wide range of possible spellings? e.g. no `toLowerCase()` since some last names have capital letters in them? )~
NOTE: Agent payload submission conforms to latest axios case transformation functionality. 
The axios changes occurred after this branch was created (I hard coded payload field names for testing and then switched them to the new API specs for the commits).
> [PRO-118] Add formstate and functionality to add an agent form

- src/components/RatingBar.tsx
- src/components/ReviewCard.tsx
- src/components/TagBadge.tsx
- src/pages/AgentView.tsx
- src/styles/colors.scss
- src/types/Agent.ts
- src/types/Review.ts
- src/types/Tag.ts
Added some space and width adjustments to the rating bars. Added the missing "Popular Tags" section in the agent view.
> Miscellaneous style adjustments

- src/loaders/resourcesLoader.ts
- src/router.tsx
- src/types/ResourceLink.ts
> [PRO-151] ResourceLoader and ResourceLink type

- src/components/List/ListItem.tsx
- src/components/ResourceCard.tsx
- src/components/SearchResult.tsx
- src/hooks/usePointerState.ts
- src/loaders/resourcesLoader.ts
- src/pages/Resources.tsx
- src/pages/Search.tsx
- src/test/components/ListItem.test.tsx
- src/test/components/__snapshots__/ListItem.test.tsx.snap
- src/types/ResourceLink.ts
* Extracted code from `SearchResult.tsx` into a generic `ListItem` component, which allows for any arrangement of children, but handles the outermost Card styles and pointer state visual feedback (hover state).
* Basic ResourceCard, with some rotating icons as placeholders for link previews from the actual resource URLs.
> [PRO-171] Resource card

- src/api/users.ts
- src/components/AccountDeleteModal.tsx
- src/pages/Account.tsx
- Adds functionality to the delete button on account page
- Asks user to confirm account deletion by entering password
- Upon successful deletion, redirects to home page
> [PRO-149] Delete account function

- src/components/ContentfulPage.tsx
- src/components/Menu/MenuLinks.tsx
- src/loaders/staticPageLoader.ts
- src/pages/Vote.tsx
- src/router.tsx
- src/util/renderRichText.tsx
This was originally a resource link, but we now have a nice article in Contentful to make a page out of. I made a wrapper for "documentToReactComponents" so all our rendered Contentful content can pass through the same customized options (I had to customize blockquotes for this).
> [PRO-177] Voting rights page

- .npmrc
- README.md
Updates to include what I needed to run the project on my machine. I haven't ever worked with pnpm so these additions may not be general. Open to feedback!
> Update readme, add .npmrc

- src/components/Resources/CategoryPill.tsx
- src/components/TagBadge.tsx
- src/styles/bootstrap-theme/badges.scss
- src/styles/bootstrap-theme/index.scss
Description
---
Mostly just making sure the default badge font is 14px and medium (500) font weight.
Before: 
---
After
---
> [PRO-186] Adjust default Badge style (font weight and size)

- public/locales/en/translation.json
- public/locales/es/translation.json
- src/components/AgentInfo.tsx
- src/components/Footer.tsx
- src/components/OfficeInfo.tsx
- src/components/PasswordResets/PasswordResetsForm.tsx
- src/components/RateAgentModal/RateAgentTag.tsx
- src/components/RateAgentModal/index.tsx
- src/components/RatingBar.tsx
- src/components/RatingRadio/RatingRadioButton.tsx
- src/components/RatingsBadge/index.tsx
- src/components/Resources/CategoryPill.tsx
- src/components/Resources/ResourceCard.tsx
- src/components/Resources/ResourceFilters.tsx
- src/components/TagBadge.tsx
- src/pages/Account.tsx
- src/pages/OfficeView.tsx
- src/pages/Vote.tsx
- src/stories/Card.stories.tsx
- src/stories/Colors.mdx
- src/styles/bootstrap-theme/buttons.scss
- src/styles/bootstrap-theme/colors.scss
- src/util/bootstrapVariables.ts
Changes
---
* Restructure colors.scss for app-wide style variables.
* Add new colors to colors.scss
* Update deprecated color names throughout app.
* Add storybook Colors page to demo the theme colors and show their names, with links to bootstrap utils.
Testing
---
Check out the deploy preview
> [PRO-204] Theme colors overhaul

- public/locales/en/translation.json
- public/locales/es/translation.json
> [PRO-227] Change placeholder text for search field

- public/locales/en/translation.json
This changes the menu item label
> Change search officers menu item to Rate My PO

- src/components/Menu/MenuLinks.tsx
- src/components/Menu/index.tsx
- src/i18n/LocaleSwitcher.tsx
Changes
---
* Restyles locale switcher to new designs
* ~~Hide for non-development (do we really want to do this?)~~
Testing
---
* Checkout this branch locally and see the switcher above the navbar
* See that it is hidden in the deploy preview (as it will be in production).
> [PRO-200] Locale switcher updates

- public/locales/en/translation.json
- public/locales/es/translation.json
- src/components/RateAgentModal/RateAgentTags.tsx
- Removes extra optional
- Adds use of translation strings
> [PRO-249] UI bug: tag section in rating modal says optional twice

- public/locales/en/translation.json
- public/locales/es/translation.json
- src/api/agents.ts
- src/components/AgentInfo.tsx
- src/components/SelectOfficeModal.tsx
- src/pages/AgentNew.tsx
- src/pages/AgentView.tsx
- src/pages/OfficeView.tsx
- src/test/components/Agent/AgentInfo.test.tsx
- src/types/Agent.ts
- Makes submission of agent's first name optional
- Adds Spanish translations for agent-related areas of the app 
- Adds tests for rendering an agent with and without a first name
> [PRO-258] Update add an agent form to allow blank field for the first

- index.html
This is a start for tracking some basic usage data. I'm viewing this as a trial of heap analytics, not 100% sure it will be the best tool for us at the free tier level, but we'll see.
> Heap Analytics

- src/api/agents.ts
- src/loaders/officeLoader.ts
- src/pages/OfficeView.tsx
Updates the list of agents to use the `Paginator` component
> [PRO-261] Paginate list of agents in officeview

- src/pages/OfficeView.tsx
- Replaces `Paginator` with react-query functionality
- Wraps office agents list in `AnimatedList`
> [PRO-271] Refactor officeview to use react query for searchable agents

- src/components/ReviewCard/ReviewCardComment.tsx
- src/components/ReviewCard/index.tsx
- src/stories/ReviewCard.stories.tsx
- src/test/components/ReviewCard.test.tsx
- src/types/Comment.ts
- src/types/Review.ts
- Adds `Comment` type
- Updates `Review` type and `ReviewCardComment` component to use `Comment` object
- Updates `ReviewCard` tests and story
> [PRO-278] Update web app to use comments rather than reviewinput

- src/components/Resources/ResourceCard.tsx
- src/pages/Resources.tsx
- src/util/mutationUpdate.ts
Changes
---
* Simplify ResourceCard to accept an `onUpdate` function.
* Adds util methods for updating react-query data (for infinite and non-infinite style query data).
Testing
---
* Resource upvoting/downvoting should work the same.
> ResourceCard updates

- public/locales/en/translation.json
- public/locales/es/translation.json
- src/components/Resources/ResourceFilters.tsx
Changes
---
* Update from "Show/Hide" filters to "Search by location or topic" (Spanish translation included)
* Express show/hide functionality with a rotating chevron icon.
English:
Spanish:
Expanded with down chevron:
Testing
---
* Peep the deploy preview
> Copy update: Resource filter toggle

- src/components/EmptyList.tsx
- src/components/SearchResultsInfo.tsx
- src/components/SelectOfficeModal.tsx
- src/pages/Resources.tsx
- Creates `EmptyList` component to handle display of user-friendly message when search results are empty
- Begins to incorporate `EmptyList` into existing components 
<h2>Testing</h2><br>
Do a bonkers search (e.g. "z") in 'Resources' and see that when no results are returned a message is displayed.
> [PRO-268] Enhance office agents list in officeview

- src/components/Resources/ResourceCard.tsx
- src/pages/ResourceView.tsx
- src/types/Resource.ts
<h2>Changes</h2>
- Adds comments count to resource card
- Adds comments icon to resource card, linking to resources details (`ResourceView`)
- Ensures comments count in `ResourceView` is updated immediately after a comment is created
<h2>Testing</h2>
**NOTE**: Depends on PRO-324 which must be merged first
1. Navigate to Resources
2. Click on comment icon on any resource card
3. Add comments to your heart's delight
4. Observe updated comments count both within the resource details page and after navigating back to Resources list.
> [PRO-320] Finish up resources card

- src/components/LoginModal/ForgotPasswordForm.tsx
- src/components/LoginModal/LoginForm.tsx
- src/components/LoginModal/SignupForm.tsx
This updates the email / password fields to explicitly make them required.
> Changing the required statements for the email and password

- src/api/passwordResets.ts
- src/components/LoginModal/index.tsx
- src/components/PasswordResets/SuccessModal.tsx
- src/pages/PasswordResets.tsx
This is the frontend changes needed for the appropriate redirect after the password reset flow.
https://github.com/ProjectProtocol/project-protocol-web/assets/5348488/d795c55e-5791-4142-9f4c-6c03e38b7b84
> Frontend changes for the redirect after the password reset

- src/components/RateAgentModal/index.tsx
Found this while porting the modal over to nextjs
> Hotfix: Remove duplicate error loop in rating modal

- src/router.tsx
This updates the legacy interface to have auth as part of the URL for the frontend, in conjunction with the change for the nextJS change.
Preview
> Legacy change to accommodate the frontend confirmations url change in the API
