ProjectProtocol/project-protocol-web

src/components/SearchBar.tsx, src/pages/Search.tsx
Problem: recent SearchBar changes broke search functionality.
Reason: without the "name" attribute, the formData wasn't about to construct the expected object (`{ search: 'xyz' }`), and so the searchLoader couldn't construct the query properly.
=> [Hotfix] Fix search

.github/workflows/tests.yml, jest.config.js, package.json, pnpm-lock.yaml, src/__tests__/util/transformKeys.test.ts, src/api/client.ts, src/api/index.ts, src/api/session.ts, src/components/RateAgentModal/RateAgentRatingRadio.tsx, src/components/RateAgentModal/form-types.ts, src/components/RateAgentModal/index.tsx, src/components/RateAgentModal/rateAgentUiStrings.ts, src/contexts/auth/AuthProvider.tsx, src/pages/Login.tsx, src/pages/Root.tsx, src/util/transformKeys.ts, tsconfig.json
* Adds Jest configuration so was can start writing tests 🚀 
* Adds `transformKeys` utility for modifying object keys.
* Adds `transformRequest` to axios config, so we can use the idiomatic `camelCase` in our JS forms and rest assured it gets converted to `snake_case`, which is the ruby idiom.
=> Api client: transforming response and request keys

package.json, pnpm-lock.yaml, src/api/passwordResets.ts, src/components/BasicPage.tsx, src/components/PasswordResets/PasswordResetsForm.tsx, src/components/PasswordResets/SuccessModal.tsx, src/pages/Confirmation.tsx, src/pages/ErrorPage.tsx, src/pages/PasswordResets.tsx, src/router.tsx, src/styles/colors.scss, src/styles/index.scss, src/styles/utils.scss
* Adds the `/password_resets/:token` page for setting a new password.
* Redirects if token is invalid (or expired)
* Normalizes full-page UIs by adding the `fullScreen` variant to BasicPage component. Currently used for both `/confirmations/<token>` and `/password_resets/<token>` routes.
Clickthrough steps are for local environment with API/mailcatcher running, and FRONTEND_HOST set to your ngrok address in the `.env` file of your rails repo.
1. Trigger password reset email via forgot password? flow (test@user.com recommended).
2. See email come through in mailcatcher
3. Click link in email and be taken to the password reset page.
4. Note that this page will redirect if the token is invalid (try changing the token), or if you try to access the page after 15 minutes (token expires after 15 …
=> [PRO-165] Password reset landing page for changing password

src/components/PopUp.tsx, src/test/components/PopUp.test.tsx, src/test/components/__snapshots__/PopUp.test.tsx.snap
Fixes a bug where closeButton was being passed along to the underlying modal component, rather than extracted for the ModalHeader component.
Clickthrough: test that this error doesn't occur when opening a modal
=> [hotfix] popup modal

package.json, pnpm-lock.yaml, src/pages/Home.tsx, src/util/bootstrapVariables.ts, src/util/loadingBar.ts
Simple solution to providing visual feedback to the user when loaders or navigation are working in the background.
The difficulties in implementing placeholders, etc, and how finicky it was to create a smooth UX for just a single view (resources) didn't sit right with me. We have a number of other pages that take a moment to load (search, agent view, etc) and creating placeholders/deferred data logic for each and every one of them seemed like a poor use of our time.
The loading indicator at the top of the page is a go-to pattern, and leveraging react-router's navigation state lets us trigger it in a central place (Home.tsx) for all navigation and loader events with a minimal amount of code. 
The deploy preview should be ready to go for a clickthrough so you can see how it looks and feels …
=> Global loading indicator

src/components/Menu/index.tsx, src/components/PasswordResets/SuccessModal.tsx, src/components/PopUp.tsx, src/components/RateAgentModal/index.tsx, src/components/SearchResult.tsx, src/components/SelectOfficeModal.tsx, src/styles/bootstrap-theme/modals.scss, src/test/components/__snapshots__/PopUp.test.tsx.snap
Description
---
First few adjustments following @peiitforward 's design review.
* Unsets the default `size="sm"` on our PopUp component. Modals still aren't perfect, but it makes a lot more sense to let them be medium-sized by default.
* Adjusts PopUp instances throughout the app to look correct after the base style adjustments.
* Adjusts color of "Project Protocol" in navbar, adds a space (Fixes PRO-190).
Screenshots
---
=> PRO-184 Modal adjustments and others

src/components/Footer.tsx, src/components/Menu/MenuLinks.tsx, src/components/Menu/index.tsx, src/components/RatingsBadge/index.tsx, src/components/RatingsBadge/svgProps.ts, src/components/Resources/ResourceCard.tsx, src/components/SearchBar.tsx, src/i18n/LocaleSwitcher.tsx, src/pages/AgentView.tsx, src/pages/Resources.tsx, src/pages/Search.tsx, src/pages/Vote.tsx, src/styles/bootstrap-theme/colors.scss, src/styles/bootstrap-theme/fonts.scss, src/styles/links.scss, src/util/renderRichText.tsx
Description
---
1. Updates bootstrap variables, particularly primary and secondary colors.
2. Updates usage of bootstrap color utilities throughout to address contrast issues from design audit.
3. Fixes a few console warnings in LocaleSwitcher (keys) and renderRichText (nested <p> tags).
Screenshots
---
Example showing new link color in content:
Resources page:
Fixes PRO-187, PRO-188, PRO-189
=> [PRO-188] Update theme colors for contrast

.storybook/i18next.ts, .storybook/main.ts, .storybook/preview.ts, package.json, pnpm-lock.yaml, public/locales/es/translation.json, src/i18n/i18n.ts
Adds `storybook-react-i18next` as a dev dependency following [this guide](https://storybook.js.org/addons/storybook-react-i18next).
1. Run storybook locally. 
2. Click on the little globe icon in the top navigation to change your locale.
3. Check out the `AgentInfo` or `OfficeInfo` stories and notice that switching locales adjust translations on the cards.
=> [PRO-192] Add Storybook translation support

src/pages/AgentView.tsx
Removes orange header in `AgentView.tsx`.
**Before**:
**After**:
=> [PRO-183] Remove orange header on agent page

package.json, pnpm-lock.yaml, src/components/Menu/index.tsx, src/components/RollbarProvider.tsx, src/main.tsx, src/pages/ErrorPage.tsx
🛠️ Changes
---
Adds Rollbar error monitoring to the React app. This adds a top-level ErrorBoundary, but 99% of the time errors are caught by the error boundary provided by `react-router-dom`. For this reason, I've added a useEffect to `<ErrorPage />` that will manually notify Rollbar of any error that isn't a well-formed response error (aka `not found`), since these are likely to be unhandled exceptions.
**Configuration explained:**
```javascript
// src/components/RollbarProvider.tsx
const rollbarConfig: Configuration = {
...
environment: import.meta.env.VITE_ENVIRONMENT || import.meta.env.MODE,
enabled: import.meta.env.PROD,
}
```
1. `environment`: will check for a VITE_ENVIRONMENT variable which will be set to `staging` and `production` on Netlify for the respective instance. Since …
=> [PRO-199] Rollbar error monitoring

src/components/Resources/CategoryPill.tsx, src/components/Resources/ResourceCard.tsx, src/components/Resources/ResourceFilters.tsx, src/components/Resources/resourceTagLabelMap.ts, src/loaders/resourcesLoader.ts, src/pages/Resources.tsx, src/types/contentful-types.ts, src/util/ContentfulClient.ts
Changes
---
*Background*: @peiitforward was kind enough to tag all of our resources using Contentful's tagging system. These
changes dynamically load all defined tags to render the resource filters, and shows the relevant tags on the resource
cards.
- Load tag list from Contentful to render resource filters
- Show all relevant tags on ResourceCards
- Report unknown tags to rollbar. Show filters on page load if a category is selected
Testing
---
Have a click around the deploy preview and make sure all resource page functionality is working.
Screenshot
---
=> [PRO-195] Use new tags in resources page

src/api/client.ts, vite.config.ts
This has a "sister" PR in the API repo: https://github.com/ProjectProtocol/project-protocol-api/pull/135
This proxy configuration effectively lets the frontend and backend share the same domain, which makes browsers happier about cookies that get set. Instead of API calls going to `http://localhost:300`, they will go to the `/api` as if it were part of the same front-end application, e.g. `https://strictly-tough-bug.ngrok-free.app/api`.
This means that the auth cookie will be set with the domain `strictly-tough-bug.ngrok-free.app`, and the browser will better know to associate it with the front-end when the user navigates to it.
In production, we have the two domains `app.projectprotocol.org` and `api.projectprotocol.org`. I think we'll have to manually set the domain of the cookie for it …
=> Configure dev server - proxy /api localhost:3000

netlify.toml, package.json, pnpm-lock.yaml, public/_redirects, src/api/client.ts
Changes
---
Adds a plugin which replaces environment variables with their defined values in the _redirects file, for proxying API calls and nice auth cookies.
```
/api/*    {{env:VITE_API_URL}}/:splat   200
/*        /index.html              200
```
gets transformed to
```
/api/*    <<actual url from environment variable>>/:splat   200
/*        /index.html              200
```
Testing
---
To test, you can open the deploy preview and open the network tab in the inspector. You'll see that API calls now go to `/api` route and are successful.
Another test, and a main reason for this proxy, is if you log in, close and reopen the browser, and navigate back to the site, you should still be logged in, because the cookie is being set with the correct domain.
=> Configuring redirect(proxy) for all Netlify environments

public/locales/en/translation.json, public/locales/es/translation.json, src/components/AddAgentCard.tsx, src/components/LoginModal/index.tsx, src/contexts/LoginUIProvider/LoginUIContext.ts, src/contexts/LoginUIProvider/index.tsx, src/contexts/auth/AuthContext.ts, src/contexts/auth/AuthProvider.tsx, src/pages/AgentNew.tsx, src/pages/Search.tsx
Changes
---
* Factor out AddAgentCard
* Update locale strings and provide translations (using [this ms tool, worth a bookmark](https://msit.powerbi.com/view?r=eyJrIjoiMmE2NjJhMDMtNTY3MC00MmI2LWFmOWUtYWM5YTVjODI5MjQwIiwidCI6IjcyZjk4OGJmLTg2ZjEtNDFhZi05MWFiLTJkN2NkMDExZGI0NyIsImMiOjV9)
* Add a signed-out state to AddAgent card for opening sign up / log in modal.
* Add ability to specify a redirect after signing in.
* Add redirect to "/" if `agents/new` is visited without signing in
* Add `isSignedIn` state to AuthProvider for clearer checks
Testing
---
* Visit site (preview is fine)
* Scroll down or enter search to view the AddAgentCard at the bottom of the results.
* Toggle en/es language to see translations
* Log in or sign up via the provided buttons
* See that you are redirected to the …
=> [PRO-233] User shouldnt be allowed to add agent without an account

public/locales/en/translation.json, public/locales/es/translation.json, src/components/AddAgentCard.tsx, src/components/ConfirmationModal.tsx, src/components/LoginModal/ForgotPasswordForm.tsx, src/components/LoginModal/LoginForm.tsx, src/components/LoginModal/SignupForm.tsx, src/components/LoginModal/index.tsx, src/components/Resources/ResourceCard.tsx, src/components/ReviewCard/ReviewCardComment.tsx, src/contexts/LoginUIProvider/LoginUIContext.ts, src/pages/AgentNew.tsx, src/pages/Search.tsx, src/styles/bootstrap-theme/colors.scss, src/test/components/AddAgentCard.test.tsx
Changes
---
* Add user.isConfirmed check. Show confirmation modal if unconfirmed.
* In `agents/new`, redirect unconfirmed users.
* Translations
* AddAgentCard.test.tsx
Testing
---
* Create or use an unconfirmed account, and click the button at the bottom of search results-- you should see the confirmation modal with an appropriate title.
=> [PRO-246] Require confirmation to add agent

public/locales/en/translation.json, public/locales/es/translation.json, src/components/Agent/RateAgentButton.tsx, src/pages/AgentView.tsx, src/test/components/Agent/RateAgentButton.test.tsx, src/types/Agent.ts
Changes
---
- Use agent.isRateable to disable rate button and show help text
- Test and more translations
Testing
---
Depends on https://github.com/ProjectProtocol/project-protocol-api/pull/138.
- Log in as confirmed user, and rate an agent.
- After posting a rating, see that the rate button is disabled with a helpful message.
=> [PRO-247] Show indiciation in ui if user must wait to rate again

src/components/Agent/RateAgentButton.tsx, src/components/AsyncButton.tsx, src/components/LoginModal/index.tsx, src/contexts/LoginUIProvider/LoginUIContext.ts, src/contexts/LoginUIProvider/index.tsx, src/pages/AgentView.tsx, src/test/components/Agent/RateAgentButton.test.tsx
- Align spinner in AsyncButton without margin
- LoginUIProvider postLogin callback, more flexible than redirectPath
- Hoist some state/functions for testability. Move unrateable to toast to avoid visual hiccups.
- Update tests
- Remove unused import
=> [PRO-250] [Bug] After signing in while viewing an agent, rate button is disabled

package.json, pnpm-lock.yaml, vite.config.ts
THis is a nice-to-have, which may or may not work. Gives better error reporting when errors
occur in the JS.
- Add vite-plugin-rollbar
- Update config with plugin when ROLLBAR_ACCESS_TOKEN is defined
=> [PRO-223] Push sourcemaps to rollbar

src/api/agents.ts
Now that results are paginated, the returned data shape is `{ data: [], meta: {...} }`, rather than just an array of items.
To be merged immediately after [PRO-262](https://github.com/ProjectProtocol/project-protocol-api/pull/145) goes live.
=> Hotfix: OfficeView fix for PRO-262

package.json, pnpm-lock.yaml, src/components/AnimatedList.tsx, src/pages/AgentView.tsx, src/stories/AnimatedList.stories.tsx
I'm plucking this out of some of the experimentation I've been doing on list handling, to reduce the number of files/changes in forthcoming PRs.
AnimatedList is meant to give us a place to have a single, canonical place to define how we want a list to render onto the screen. This branch adds a story and uses it for the list of reviews on an agent.
Changes
---
* Adds [react-spring animation library](https://www.react-spring.dev/) -- very powerful and concise animation library I've worked with lots in the past.
* Adds an AnimatedList component which wraps all direct children in an animated container.
* Wrap agent reviews in AnimatedList in the AgentView.
Testing
---
* In the deploy preview, wiew a few agents with multiple reviews to see the AnimatedList in action.
* (optional) You can fire …
=> Animated list component

public/locales/en/translation.json, public/locales/es/translation.json, src/api/resources.ts, src/components/LocaleSwitcher.tsx, src/components/NotificationArea.tsx, src/components/Resources/ResourceCard.tsx, src/components/Resources/ResourceVoteControls.tsx, src/pages/Resources.tsx, src/stories/Colors.mdx, src/test/components/LocaleSwitcher.test.tsx, src/test/components/Resources/ResourceVoteControls.test.tsx, src/types/Resource.ts, src/types/SearchMeta.ts
Changes
---
* Add resource like/dislike API client functions
* Add ResourceVoteControls component and test, for showing and updating like/dislike counts.
* Show toast when user is not authenticated
* Truncate resource description if more than 100 characters. TODO: translate Show more/less and get design feedback.
Testing:
---
* Try liking/disliking when not signed in
* Try liking/disliking when signed in
* Check that counts update and make sense.
📸 Screenshots
---
Outline icons when user hasn't voted on a resource:
Filled in icons when user has voted:
Alert when not signed in:
en Español:
=> [PRO-296] Resource likes/dislikes UI

public/locales/es/translation.json
Fixes typo in Spanish copy. It appears the original was supposed to be "su" (maybe to capture the plural sense of "you all").
We tend to address the user with the familiar "tu" in majority of the app, so I edited accordingly; but there are inconsistencies in our usage which need to be addressed eventually.
=> copy-fix-4-22-24

public/locales/en/translation.json, public/locales/es/translation.json
Changes "Availability" to "Available" for grammatical consistency across agent rating categories (all the others are adjectives).
<h3>Before</h3>
<h3>After</h3>
=> [PRO-300] Change agent rating category "Availability" to "Available"

.github/pull_request_template.md, scripts/tolgee-pull
We didn't specify a tolgee/cli version in the script. The script was using options that only existed before v2 but the Netlify build process was installing the latest one (v2.0.1). I had v1.4.0 installed locally somehow. This adds an explicit version to the script so this shouldn't happen again.
- Pin tolgee/cli to version and update command syntax
- Add pull-request template while I'm at it
=> Hotfix: tolgee script

src/pages/AgentView.tsx
* Fixed translated string missing namespace for confirmation modal.
1. Create an account
2. Do not confirm
3. Log into account
4. Go to rate an agent
5. It should pop up the confirmation modal with the broken title.
=> [PRO-331] Fixes confirmation modal title

src/components/RateAgentModal/index.tsx
This updates the Submit text to use Submit for review only if a person has entered anything in the review input. Otherwise, Submit is used.
Start off with blank comment
Start typing something
=> Changing the submit message based on comment entered

src/components/RateAgentModal/index.tsx
Adding a tooltip (using Popover) as a way to explain why additional comments are hidden until approved. The text is in Tolgee and can be workshopped. 
On hover next to the icon, this popup shows up.
=> Adding a tooltip for help guidelines for additional comments

src/components/RateAgentModal/index.tsx
We do not want people who are rating their current officer to add comments. This adds a radio selection that when toggled, will affect the disabled state of the comments form area (turn the text muted, update the form placeholder text).
=> Adding a safeguard at the end of the rate agent modal for checking current parole

src/components/LoginModal/index.tsx, src/pages/PasswordResets.tsx
The Tolgee key should not have any spaces, so if there is a space, then we use that message as / is vs. using the Tolgee translation. In addition, I noticed that there were several places in the API layer that required Tolgee usage rather than raw strings, so I replaced them with their counterparts.
=> Front End changes to support Tolgee usage of password reset

src/api/profile.ts, src/components/ModerationInfoModal.tsx, src/pages/AgentView.tsx, src/pages/Search.tsx, src/types/User.ts
This uses the moderation modal to display when a user logs in and hasn't yet acknowledged policy yet. It then doesn't display again when the user navigates back to another page. It is slightly modified from the version shown to users after they leave a comment.
=> Frontend implementation of the policy acknowledged field

src/pages/NotFound.tsx, src/router.tsx
Mistyped urls were causing an error to be thrown. This catches unknown paths in the router and shows a Not found page.
Error: https://app.rollbar.com/a/tasandberg/fix/item/project-protocol-web/39
* Visit https://deploy-preview-143--fabulous-sprite-a61e48.netlify.app/resourcves
=> Not found route and page
